name: Build and deploy

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "*.md"
      - LICENSE

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install npm/nodejs
        uses: actions/setup-node@v4

      - name: Install packages
        run: npm ci

      - name: build
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}